filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
filebeat.modules:

#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true
#=========================== Filebeat inputs =============================

logging.json: true
logging.level: info
logging.to_files: false
logging.to_stderr: true
logging.metrics_enabled: false

filebeat.inputs:

  # Each - is an input. Most options can be set at the input level, so
  # you can use different inputs for various configurations.
  # Below are the input specific configurations.
  - type: log

    # Change to true to enable this input configuration.
    enabled: true

    # Paths that should be crawled and fetched. Glob based paths.
    paths:
      - '/usr/src/app/log/responder_service.log'

    json.keys_under_root: true
    json.add_error_key: true
    exclude_files: ['.gz$']

setup.dashboards.enabled: '${SETUP_KIBANA_DASHBOARDS:false}'
setup.kibana.host: '${KIBANA_HOST:https://kibana.hosts.rxrevu.com:5601/app/kibana}'
setup.kibana.ssl.enabled: '${ELASTICSEARCH_SSL_ENABLED:true}'
setup.kibana.ssl.supported_protocols: [TLSv1.2]
setup.kibana.ssl.verification_mode: none
setup.template.settings:

  # A dictionary of settings to place into the settings.index dictionary
  # of the Elasticsearch template. For more details, please check
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
  index:
    number_of_shards: 1
    codec: best_compression
    #number_of_routing_shards: 30

  # A dictionary of settings for the _source field. For more details, please check
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html
  _source:
    enabled: true


#============================== Setup ILM =====================================

# Configure index lifecycle management (ILM). These settings create a write
# alias and add additional settings to the index template. When ILM is enabled,
# output.elasticsearch.index is ignored, and the write alias is used to set the
# index name.
ilm.enabled: true
# Enable ILM support. Valid values are true, false, and auto. When set to auto
# (the default), the Beat uses index lifecycle management when it connects to a
# cluster that supports ILM; otherwise, it creates daily indices.
setup.ilm.enabled: true

# Set the prefix used in the index lifecycle write alias name. The default alias
# name is 'filebeat-%{[agent.version]}'.
setup.ilm.rollover_alias: "filebeat-%{[agent.version]}"

# Set the rollover index pattern. The default is "%{now/d}-000001".
setup.ilm.pattern: "{now/d}-000001"

# Set the lifecycle policy name. The default policy name is
# 'filebeat-%{[agent.version]}'.
#setup.ilm.policy_name: "mypolicy"

# The path to a JSON file that contains a lifecycle policy configuration. Used
# to load your own lifecycle policy.
#setup.ilm.policy_file:

# Disable the check for an existing lifecycle policy. The default is false. If
# you disable this check, set setup.ilm.overwrite: true so the lifecycle policy
# can be installed.
setup.ilm.check_exists: true

# Overwrite the lifecycle policy at startup. The default is false.
setup.ilm.overwrite: true

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name: elk-demo

# The tags of the shipper are included in their own field with each
# transaction published.
tags: ["production_responder_service"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: '${RAILS_ENV}'

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"
setup.template.overwite: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:https://es-data.corp.rxrevu.com:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_NEW_PASSWORD:}'
  # Use SSL settings for HTTPS.
  ssl.enabled: '${ELASTICSEARCH_SSL_ENABLED:true}'

  # Configure SSL verification mode. If `none` is configured, all server hosts
  # and certificates will be accepted. In this mode, SSL-based connections are
  # susceptible to man-in-the-middle attacks. Use only for testing. Default is
  # `full`.
  ssl.verification_mode: none

  # List of supported/valid TLS versions. By default all TLS versions from 1.0 up to
  # 1.2 are enabled.
  ssl.supported_protocols: [TLSv1.2]

  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/elastic-stack-ca.crt.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client certificate key
  #ssl.key: "/etc/pki/client/cert.key"

  # Optional passphrase for decrypting the certificate key.
  #ssl.key_passphrase: ''

  # Configure cipher suites to be used for SSL connections
  #ssl.cipher_suites: []

  # Configure curve types for ECDHE-based cipher suites
  #ssl.curve_types: []

  # Configure what types of renegotiation are supported. Valid options are
  # never, once, and freely. Default is never.
  #ssl.renegotiation: never
  enabled: true

queue.spool:
  file:
    path: "${path.data}/spool.dat"
    size: 4GiB
    page_size: 16KiB
  write:
    buffer_size: 10MiB
    flush.timeout: 5s
    flush.events: 1024

