name: pertask-metricbeat-${SERVICE_ENVIRONMENT}-${HOSTNAME}
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.max_start_delay: 10s


#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  _source.enabled: true

setup.dashboards.enabled: '${SETUP_KIBANA_DASHBOARDS:false}'
setup.kibana.host: '${KIBANA_HOST:https://kibana.hosts.rxrevu.com:5601/app/kibana}'
setup.kibana.ssl.enabled: '${ELASTICSEARCH_SSL_ENABLED:true}'
setup.kibana.ssl.supported_protocols: [TLSv1.2]
setup.kibana.ssl.verification_mode: none

logging.json: true
logging.level: info
logging.to_files: false
logging.to_stderr: true
logging.metrics_enabled: false
#output.console:
#  pretty: false
metricbeat.modules:
  - module: HTTP
    period: 5s
    metricsets:
      - json
    namespace: "fargate_metrics"
    hosts: ["169.254.170.2:80"]
    path: "/v2/stats"
    #json.is_array: true
    headers:
      Accept: "application/json"
  - module: HTTP
    period: 30s
    metricsets:
      - json
    namespace: "fargate_metadata"
    hosts: ["169.254.170.2:80"]
    path: "/v2/metadata"
    #json.is_array: true
    headers:
      Accept: "application/json"
  - module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - socket_summary  # Socket summary
      - core           # Per CPU core usage
      - diskio         # Disk IO
      - filesystem     # File system usage for each mountpoint
      - fsstat         # File system summary metrics
      #- raid           # Raid
      - socket         # Sockets and connection info (linux only)
    enabled: true
    period: 5s
    processes: ['.*']
    # Configure the metric types that are included by these metricsets.
    cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
    core.metrics: ["percentages"]  # The other available option is ticks.
tags: ["production_responder_service"]
processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~

ilm.enabled: true
setup.ilm.enabled: true
setup.ilm.rollover_alias: "metricbeat-%{[agent.version]}"
setup.ilm.policy_name: "metricbeat-%{[agent.version]}"
setup.template.name: "metricbeat-%{[agent.version]}"
setup.template.pattern: "metricbeat-%{[agent.version]}-*"
setup.template.overwite: false

output.elasticsearch:
  # Array of hosts to connect to.
#  hosts: 'https://es-data.corp.rxrevu.com:9200'
  hosts: '${ELASTICSEARCH_HOSTS:https://es-data.corp.rxrevu.com:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_NEW_PASSWORD}'
  protocol: "http"
  ssl.enabled: '${ELASTICSEARCH_SSL_ENABLED:true}'
  #ssl.certificate_authorities: ["/etc/beats/ssl/identity-ca-chain.pem", "/etc/beats/ssl/component-ca-chain.pem"]
  #ssl.certificate: "/etc/beats/ssl/new-corp.rxrevu.com.crt"
  #ssl.key: "/etc/beats/ssl/new-corp.rxrevu.com.key"
  ssl.supported_protocols: [TLSv1.2]
  ssl.verification_mode: none
  enabled: true



queue.spool:
  file:
    path: "${path.data}/spool.dat"
    size: 4GiB
    page_size: 16KiB
  write:
    buffer_size: 10MiB
    flush.timeout: 5s
    flush.events: 1024


